version: '3.4'

services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:8080
    expose:
      - 8080
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:8000
      - ASPNETCORE_HOSTINGSTARTUPASSEMBLIES=Microsoft.AspNetCore.SpaProxy
    expose:
      - 44464
      - 8000
    ports:
      - "44464:44464"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
