version: '3.4'

services:
  api:
    image: ${REGISTRY:-calc}/arithmetics.api:${TAG:-latest}
    build:
      context: .
      dockerfile: Calculator.Services.ArithmeticOperations/Dockerfile
    container_name: calc-api
    networks:
      - calc-dapr
  api-dapr:
    image: "daprio/daprd"
    container_name: calc-api-darp
    command: ["./daprd",
      "-app-id", "api",
      "-app-port", "80",
      "-placement-host-address", "placement:50006",]
    network_mode: "service:api"

  web:
    image: ${REGISTRY:-calc}/web:${TAG:-latest}
    build:
      context: .
      dockerfile: Calculator.Web/Dockerfile
    container_name: calc-web
    networks:
      - calc-dapr
  web-dapr:
    image: "daprio/daprd"
    container_name: calc-web-darp
    command: ["./daprd",
      "-app-id", "web",
      "-app-port", "80",
      "-placement-host-address", "placement:50006",
      "-components-path", "/components" ]
    depends_on:
      - redis
    volumes:
      - "./dapr-components/:/components"
    network_mode: "service:web"

  ### Redis state store
  redis:
    image: redis:alpine
    container_name: calc-state
    ports:
      - "6379:6379"
    expose:
      - 6379
    networks:
      - calc-dapr

  placement:
    image: "daprio/dapr"
    container_name: calc-placement
    command: ["./placement", "-port", "50006"]
    ports:
      - "50006:50006"
    networks:
      - calc-dapr

networks:
    calc-dapr:
