version: '3.4'

services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - NODE_ENV=development
    expose:
      - 44464
    ports:
      - "80:80"
      - "44464:44464"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
