version: '3.4'

services:
  api:
    image: ${REGISTRY:-calc}/arithmetics.api:${TAG:-latest}
    build:
      context: .
      dockerfile: Calculator.Services.ArithmeticOperations/Dockerfile
    container_name: calc-api
    networks:
      - calc-dapr

  web:
    image: ${REGISTRY:-calc}/web:${TAG:-latest}
    build:
      context: .
      dockerfile: Calculator.Web/Dockerfile
    container_name: calc-web
    networks:
      - calc-dapr

  dapr:
    image: "daprio/daprd"
    container_name: calc-darp
    command: ["./daprd",
        "-app-id", "web",
        "-dapr-http-port", "3500",
        "-components-path", "/components",
        "-allowed-origins", "http://localhost:44464"]
    expose:
      - 3500
    depends_on:
      - redis
    volumes:
      - "./.docker/dapr-components/:/components"
    networks:
      - calc-dapr

  proxy:
    image: nginx:latest
    container_name: calc-proxy
    ports:
      - "80:80"
    depends_on:
      - web
      - dapr
      - api
    volumes:
      - ./.docker/nginx.proxy.conf:/etc/nginx/nginx.conf
    networks:
      - calc-dapr

  ### Redis state store
  redis:
    image: redis:alpine
    container_name: calc-state
    ports:
      - "6379:6379"
    expose:
      - 6379
    networks:
      - calc-dapr

networks:
    calc-dapr: