name: microservice
registry: myregistry.azurecr.io
extensions:
- name: dapr

  # log-level configures the log level of the dapr sidecar
  log-level: debug

  # components-path configures the components path of the dapr side card
  components-path: "./.docker/dapr-components/"
ingress:
  - name: ingress
    bindings:
      - port: 8080
    rules:
      - path: /
        service: frontend
      - path: /api
        service: backend
services:
- name: frontend
  project: Calculator.Web/Calculator.Web.csproj
- name: backend
  project: Calculator.Services.ArithmeticOperations/Calculator.Services.ArithmeticOperations.csproj
- name: redis
  image: redis
  bindings:
    - port: 6379
      connectionString: ${host}:${port}