name: Build and Test

on:
  push:
    branches-ignore: [main]

jobs:
  dotnet-build-test:
    name: dotnet tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK 6
        uses: actions/setup-dotnet@v1.8.0
        with:
          dotnet-version: '6.0.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Build and Test with coverage
        run: >
          dotnet test --no-restore -c Debug
          -l:"trx;LogFileName=../../../TestResults/arithmetic-operations.unit-tests.trx"
          src/Calculator.Services.ArithmeticOperations.Tests/Calculator.Services.ArithmeticOperations.Tests.csproj
          /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput="../../TestResults/"
      - name: Upload dotnet test results
        uses: actions/upload-artifact@v2
        with:
          name: dotnet-test-results
          path: TestResults
        if: ${{ always() }}
  web-lint-test:
    name: web lint and tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Node Modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
      - name: npm package install
        run: npm ci --prefix ./src/Calculator.Web/calculator-app --cache ~/.npm --prefer-offline --no-audit --silent
      - name: web lint
        run: npm run lint --prefix ./src/Calculator.Web/calculator-app
        continue-on-error: true
      - name: web tests
        run: npm run test --prefix ./src/Calculator.Web/calculator-app
      - name: upload web test results
        uses: actions/upload-artifact@v2
        with:
          name: web-test-results
          path: TestResults
        if: ${{ always() }}
  dotnet-format:
    name: dotnet lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1.8.0
        with:
          dotnet-version: '6.0.x'
      - name: format whitespace
        run: dotnet format whitespace --verify-no-changes
      - name: format style
        run: dotnet format style --verify-no-changes
  spell-check:
    name: spell check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npx cspell --no-progress "**/*"
  git-leaks:
    name: secrets detection
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '2'
      - uses: zricethezav/gitleaks-action@master
  editorconfig-check:
    name: .editorconfig lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: editorconfig-checker/action-editorconfig-checker@v1
  markdown-lint:
    name: markdown lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npx markdownlint-cli **/*.md --ignore **/node_modules/**
  contract-testing:
    name: contract tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build api in docker
        run: docker build --no-cache -t calc/arithmetics.api:local -f src/Calculator.Services.ArithmeticOperations/Dockerfile src/
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'calc/arithmetics.api:local'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
      - name: Build web in docker
        run: docker build --no-cache -t calc/arithmetics.web:local -f src/Calculator.Web/Dockerfile src/
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'calc/arithmetics.web:local'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
      - name: Redis run and tests
        uses: shogo82148/actions-setup-redis@v1
        with:
          redis-version: '6.x'
        run: redis-cli ping
      - name: Run api in docker
        run: docker run -d -p "80:80" --rm --name=api-local-instance-for-contract-testing calc/arithmetics.api:local
      - name: Contract tests
        run: npx dredd arithmetic-api.contract-tests.yml http://localhost -l error
      - run: docker stop api-local-instance-for-contract-testing
      - run: docker rmi calc/arithmetics.api:local
  dependency-check:
    runs-on: ubuntu-latest
    name: dependency check
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK 6
        uses: actions/setup-dotnet@v1.8.0
        with:
          dotnet-version: '6.0.x'
      - name: Build dotnet projects
        run: dotnet build -c Debug src/Calculator.Services.ArithmeticOperations.Tests/Calculator.Services.ArithmeticOperations.Tests.csproj
      - uses: dependency-check/Dependency-Check_Action@main
        id: dependency-check
        with:
          project: 'template'
          path: '**/bin/Debug/net5.0/**/*.dll'
          format: 'JUNIT'
          args: >
            --scan "**/calculator-app/package*.json"
            --junitFailOnCVSS 7
      - name: upload check results
        uses: actions/upload-artifact@v2
        with:
          name: dependency-check-results
          path: ${{github.workspace}}/reports
        if: ${{ always() }}
  docker-metadata:
    runs-on: ubuntu-latest
    name: Extract Docker metadata
    steps:
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ matrix.services.imageName }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=ref,event=branch
            type=sha
  sonar-cloud:
    name: sonar cloud analysis
    runs-on: ubuntu-latest
    needs:
      - dotnet-build-test
      - dotnet-format
      - web-lint-test
      - spell-check
      - git-leaks
      - editorconfig-check
      - contract-testing
      - dependency-check
      - markdown-lint
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache SonarCloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v1
        with:
          path: ./.sonar/scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner
      - name: Setup .NET Core SDK 3
        uses: actions/setup-dotnet@v1.8.0
        with:
          dotnet-version: 3.1.x
      - name: Setup .NET Core SDK 6
        uses: actions/setup-dotnet@v1.8.0
        with:
          dotnet-version: '6.0.x'
      - name: Install SonarCloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        run: |
          mkdir -p ./.sonar/scanner
          dotnet tool update dotnet-sonarscanner --tool-path ./.sonar/scanner
      - name: Download api test results
        id: download-api-tests
        uses: actions/download-artifact@v2
        with:
          name: dotnet-test-results
          path: TestResults
      - name: Download web test results
        id: download-web-tests
        uses: actions/download-artifact@v2
        with:
          name: web-test-results
          path: TestResults
      - name: Download dependency check
        id: download-dependency-results
        uses: actions/download-artifact@v2
        with:
          name: dependency-check-results
          path: TestResults
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./.sonar/scanner/dotnet-sonarscanner begin /k:"MentorMate_dotnet-containers-template" /o:mentormate \
           /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url=https://sonarcloud.io \
           /d:sonar.exclusions="**/node_modules/**/*,**/*.ttf,**/*.woff2,**/Scripts/**/*,**/bootstrap*.css" \
           /d:sonar.test.inclusions="src/Calculator.Services.ArithmeticOperations.Tests/**/*,**/*.test.ts,**/calculator-e2e/**/*" \
           /d:sonar.cs.opencover.reportsPaths="${{steps.download-api-tests.outputs.download-path}}/coverage.opencover.xml" \
           /d:sonar.cs.vstest.reportsPaths="${{steps.download-api-tests.outputs.download-path}}/arithmetic-operations.unit-tests.trx" \
           /d:sonar.testExecutionReportPaths="${{steps.download-web-tests.outputs.download-path}}/test-report.xml" \
           /d:sonar.javascript.lcov.reportPaths="${{steps.download-web-tests.outputs.download-path}}/lcov.info" \
           /d:sonar.junit.reportPaths="${{steps.download-dependency-results.outputs.download-path}}/dependency-check-junit.xml"
          dotnet build
          ./.sonar/scanner/dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
  security:
    name: security
    runs-on: ubuntu-latest
    needs:
      - dotnet-build-test
      - dotnet-format
      - web-lint-test
      - spell-check
      - git-leaks
      - editorconfig-check
      - contract-testing
      - dependency-check
      - markdown-lint
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/dotnet@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
           args: --file=/github/workspace/Calculator.sln
  Notification:
    needs:
      - dotnet-build-test
      - dotnet-format
      - web-lint-test
      - spell-check
      - git-leaks
      - editorconfig-check
      - contract-testing
      - dependency-check
      - markdown-lint
      - security
    steps:
      - name: Google Chat Notification
        uses: Co-qn/google-chat-notification@releases/v1
        with:
          name: Build
          url: "https://chat.googleapis.com/v1/spaces/AAAAQcCmYQY/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=aacP7-Ah-kT9ZgdmI1ahr_phNJGI24_rS06ai-aK24g%3D"
          status: ${{ job.status }}
        if: always()
