name: Integration (Automatic)

on:
  push:
    branches:
      - main
      - ci
      - 'release/**'
      - 'hotfix/**'
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main, release/**]

jobs:
  dotnet-build-test:
    name: dotnet tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK 6
        uses: actions/setup-dotnet@v1.8.0
        with:
          dotnet-version: '6.0.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Build and Test with coverage
        run: >
          dotnet test --no-restore -c Debug
          -l:"trx;LogFileName=../../../TestResults/arithmetic-operations.unit-tests.trx"
          src/Calculator.Services.ArithmeticOperations.Tests/Calculator.Services.ArithmeticOperations.Tests.csproj
          /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput="../../TestResults/"
      - name: Upload dotnet test results
        uses: actions/upload-artifact@v2
        with:
          name: dotnet-test-results
          path: TestResults
        if: ${{ always() }}
  web-lint-test:
    name: web lint and tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Node Modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
      - name: npm package install
        run: npm ci --prefix ./src/Calculator.Web/calculator-app --cache ~/.npm --prefer-offline --no-audit --silent
      - name: web lint
        run: npm run lint --prefix ./src/Calculator.Web/calculator-app
        continue-on-error: true
      - name: web tests
        run: npm run test --prefix ./src/Calculator.Web/calculator-app
      - name: upload web test results
        uses: actions/upload-artifact@v2
        with:
          name: web-test-results
          path: TestResults
        if: ${{ always() }}
  dotnet-format:
    name: dotnet lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1.8.0
        with:
          dotnet-version: '6.0.x'
      - name: format whitespace
        run: dotnet format whitespace --verify-no-changes
      - name: format style
        run: dotnet format style --verify-no-changes
  spell-check:
    name: spell check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npx cspell --no-progress "**/*"
  git-leaks:
    name: secrets detection
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '2'
      - uses: zricethezav/gitleaks-action@master
  editorconfig-check:
    name: .editorconfig lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: editorconfig-checker/action-editorconfig-checker@v1
  markdown-lint:
    name: markdown lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npx markdownlint-cli **/*.md --ignore **/node_modules/**
  contract-testing:
    name: contract tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build api in docker
        run: docker build --no-cache -t calc/arithmetics.api:local -f src/Calculator.Services.ArithmeticOperations/Dockerfile src/
      - name: Run api in docker
        run: docker run -d -p "80:80" --rm --name=api-local-instance-for-contract-testing calc/arithmetics.api:local
      - name: Contract tests
        run: npx dredd arithmetic-api.contract-tests.yml http://localhost -l error
      - run: docker stop api-local-instance-for-contract-testing
      - run: docker rmi calc/arithmetics.api:local
  # redis:
  #   name: redis
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Redis run and tests
  #       uses: shogo82148/actions-setup-redis@v1
  #       with:
  #         redis-version: '6.x'
  #     - run: redis-cli ping
  dependency-check:
    runs-on: ubuntu-latest
    name: dependency check
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK 6
        uses: actions/setup-dotnet@v1.8.0
        with:
          dotnet-version: '6.0.x'
      - name: Cache Node Modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
      - name: npm package install
        run: npm ci --prefix ./src/Calculator.Web/calculator-app --cache ~/.npm --prefer-offline --no-audit --silent
      - name: Build dotnet projects
        run: dotnet build -c Debug src/Calculator.Services.ArithmeticOperations.Tests/Calculator.Services.ArithmeticOperations.Tests.csproj
      - uses: dependency-check/Dependency-Check_Action@main
        id: dependency-check
        with:
          project: 'template'
          path: '**/bin/Debug/net6.0/**/*.dll'
          format: 'JUNIT'
          args: >
            --scan "**/calculator-app/package*.json"
            --junitFailOnCVSS 7
      - name: upload check results
        uses: actions/upload-artifact@v2
        with:
          name: dependency-check-results
          path: ${{github.workspace}}/reports
        if: ${{ always() }}
  sonar-cloud:
    name: sonar cloud analysis
    runs-on: ubuntu-latest
    outputs:
      job-status: ${{ steps.stepid.outputs.job-status }}
    needs:
      - dotnet-build-test
      - dotnet-format
      - web-lint-test
      - spell-check
      - git-leaks
      - editorconfig-check
      - contract-testing
      - dependency-check
      - markdown-lint
      #- redis
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache SonarCloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v1
        with:
          path: ./.sonar/scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner
      - name: Setup .NET Core SDK 3
        uses: actions/setup-dotnet@v1.8.0
        with:
          dotnet-version: 3.1.x
      - name: Setup .NET Core SDK 6
        uses: actions/setup-dotnet@v1.8.0
        with:
          dotnet-version: '6.0.x'
      - name: Install SonarCloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        run: |
          mkdir -p ./.sonar/scanner
          dotnet tool update dotnet-sonarscanner --tool-path ./.sonar/scanner
      - name: Download api test results
        id: download-api-tests
        uses: actions/download-artifact@v2
        with:
          name: dotnet-test-results
          path: TestResults
      - name: Download web test results
        id: download-web-tests
        uses: actions/download-artifact@v2
        with:
          name: web-test-results
          path: TestResults
      - name: Download dependency check
        id: download-dependency-results
        uses: actions/download-artifact@v2
        with:
          name: dependency-check-results
          path: TestResults
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./.sonar/scanner/dotnet-sonarscanner begin /k:"mm-dotnet-containers-template-github" /o:mentormate \
           /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url=https://sonarcloud.io \
           /d:sonar.exclusions="**/node_modules/**/*,**/*.ttf,**/*.woff2,**/Scripts/**/*,**/bootstrap*.css" \
           /d:sonar.test.inclusions="src/Calculator.Services.ArithmeticOperations.Tests/**/*,**/*.test.ts,**/calculator-e2e/**/*" \
           /d:sonar.cs.opencover.reportsPaths="${{steps.download-api-tests.outputs.download-path}}/coverage.opencover.xml" \
           /d:sonar.cs.vstest.reportsPaths="${{steps.download-api-tests.outputs.download-path}}/arithmetic-operations.unit-tests.trx" \
           /d:sonar.testExecutionReportPaths="${{steps.download-web-tests.outputs.download-path}}/test-report.xml" \
           /d:sonar.javascript.lcov.reportPaths="${{steps.download-web-tests.outputs.download-path}}/lcov.info" \
           /d:sonar.junit.reportPaths="${{steps.download-dependency-results.outputs.download-path}}/dependency-check-junit.xml"
          dotnet build
          ./.sonar/scanner/dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
      - id: stepid
        run: echo "::set-output name=job-status::Success"

  # snyk:
  #   runs-on: ubuntu-latest
  #   needs:
  #     - dotnet-build-test
  #     - dotnet-format
  #     - web-lint-test
  #     - spell-check
  #     - git-leaks
  #     - editorconfig-check
  #     - contract-testing
  #     - dependency-check
  #     - markdown-lint
  #     - redis
  #   steps:
  #     - uses: actions/checkout@master
  #     - name: Run Snyk to check for vulnerabilities
  #       uses: snyk/actions/dotnet@master
  #       continue-on-error: true # To make sure that SARIF upload gets called
  #       env:
  #         SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  #       with:
  #          args: --file=/github/workspace/Calculator.sln
  notification-pre-deploy:
    name: '>'
    if: ${{ always() && github.ref != 'refs/heads/main' }}
    needs: [sonar-cloud]
    uses: ./.github/workflows/notify-reusable-action.yml
    with:
      job-status: ${{needs.sonar-cloud.outputs.job-status}}
    secrets:
      GOOGLE_WEBHOOK: ${{ secrets.GOOGLE_WEBHOOK }}

  doc-fx:
    name: documentation wiki
    if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/ci')  }}
    runs-on: windows-2022
    needs:
      - dotnet-build-test
      - dotnet-format
      - web-lint-test
      - spell-check
      - git-leaks
      - editorconfig-check
      - contract-testing
      - dependency-check
      - markdown-lint
      #- redis
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK 6
        uses: actions/setup-dotnet@v1.8.0
        with:
          dotnet-version: '6.0.x'
      - name: Setup DocFX
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install docfx
      - name: Install dependencies
        run: dotnet restore
      - name: DocFX Metadata
        run: docfx metadata .docs/docfx.json
      - name: DocFX Build
        run: docfx .docs/docfx.json
      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .docs/_site
          force_orphan: true
  publish:
    name: build and push docker
    if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/ci')  }}
    needs:
      - dotnet-build-test
      - dotnet-format
      - web-lint-test
      - spell-check
      - git-leaks
      - editorconfig-check
      - contract-testing
      - dependency-check
      - markdown-lint
      #- redis
    runs-on: ubuntu-latest
    strategy:
      matrix:
        services: [
          { 'imageName': 'calc-api', 'file': './src/Calculator.Services.ArithmeticOperations/Dockerfile' },
          { 'imageName': 'calc-web', 'file': './src/Calculator.Web/Dockerfile' }
        ]
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    permissions:
      packages: write
      contents: read
    outputs:
      calcApiImage: ${{ steps.image-tag.outputs.image-calc-api }}
      calcWebImage: ${{ steps.image-tag.outputs.image-calc-web }}
    steps:
      - uses: actions/checkout@v2
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ matrix.services.imageName }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=ref,event=branch
            type=sha
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./src
          file: ${{ matrix.services.file }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Output image tag
        id: image-tag
        run: echo "::set-output name=image-${{ matrix.services.imageName }}::${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ matrix.services.imageName }}:sha-$(git rev-parse --short HEAD)" | tr '[:upper:]' '[:lower:]'
      - run: echo IMAGE_NAMElower=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAMElower }}/${{ matrix.services.imageName }}:main
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
  deploy-integration:
    name: Integration
    needs: [publish]
    uses: ./.github/workflows/deploy-reusable-action.yml
    with:
      ENV_NAME: integration
      WEB_DOCKER_IMAGE: ghcr.io/${{ github.repository }}/calc-web:sha-$(git rev-parse --short HEAD)
      API_DOCKER_IMAGE: ghcr.io/${{ github.repository }}/calc-api:sha-$(git rev-parse --short HEAD)
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_SUBSCRIPTION: ${{ secrets.AZURE_SUBSCRIPTION }}
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASS: ${{ secrets.DOCKER_TOKEN }}
  create-tag:
    name: create new tag
    runs-on: ubuntu-latest
    outputs:
      job-status: ${{ steps.stepid.outputs.job-status }}
      tag-version: ${{ steps.tag_version.outputs.new_tag }}
    needs:
      - deploy-integration
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - id: stepid
        run: echo "::set-output name=job-status::Success"

  notification:
    name: '>'
    if: ${{ always() && github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/ci') }}
    needs: [create-tag]
    uses: ./.github/workflows/notify-reusable-action.yml
    with:
      job-status: ${{needs.create-tag.outputs.job-status}}
    secrets:
      GOOGLE_WEBHOOK: ${{ secrets.GOOGLE_WEBHOOK }}
