name: Build and Test

on:
  push:
    branches: [main, release-*]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main, release-*]

jobs:
  dotnet-build-test:
    name: dotnet tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK 6
        uses: actions/setup-dotnet@v1.8.0
        with:
          dotnet-version: '6.0.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Build and Test with coverage
        run: >
          dotnet test --no-restore -c Debug
          -l:"trx;LogFileName=../../../TestResults/arithmetic-operations.unit-tests.trx"
          src/Calculator.Services.ArithmeticOperations.Tests/Calculator.Services.ArithmeticOperations.Tests.csproj
          /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput="../../TestResults/"
      - name: Upload dotnet test results
        uses: actions/upload-artifact@v2
        with:
          name: dotnet-test-results
          path: TestResults
        if: ${{ always() }}
  web-lint-test:
    name: web lint and tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Node Modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
      - name: npm package install
        run: npm ci --prefix ./src/Calculator.Web/calculator-app --cache ~/.npm --prefer-offline --no-audit --silent
      - name: web lint
        run: npm run lint --prefix ./src/Calculator.Web/calculator-app
        continue-on-error: true
      - name: web tests
        run: npm run test --prefix ./src/Calculator.Web/calculator-app
      - name: upload web test results
        uses: actions/upload-artifact@v2
        with:
          name: web-test-results
          path: TestResults
        if: ${{ always() }}
  dotnet-format:
    name: dotnet lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1.8.0
        with:
          dotnet-version: '6.0.x'
      - name: format whitespace
        run: dotnet format whitespace --verify-no-changes
      - name: format style
        run: dotnet format style --verify-no-changes
  spell-check:
    name: spell check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npx cspell --no-progress "**/*"
  git-leaks:
    name: secrets detection
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '2'
      - uses: zricethezav/gitleaks-action@master
  editorconfig-check:
    name: .editorconfig lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: editorconfig-checker/action-editorconfig-checker@v1
  markdown-lint:
    name: markdown lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npx markdownlint-cli **/*.md --ignore **/node_modules/**
  contract-testing:
    name: contract tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build api in docker
        run: docker build --no-cache -t calc/arithmetics.api:local -f src/Calculator.Services.ArithmeticOperations/Dockerfile src/
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'calc/arithmetics.api:local'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
      - name: Build web in docker
        run: docker build --no-cache -t calc/arithmetics.web:local -f src/Calculator.Web/Dockerfile src/
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'calc/arithmetics.web:local'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
      - name: Redis run and tests
        uses: shogo82148/actions-setup-redis@v1
        with:
          redis-version: '6.x'
        run: redis-cli ping
      - name: Run api in docker
        run: docker run -d -p "80:80" --rm --name=api-local-instance-for-contract-testing calc/arithmetics.api:local
      - name: Contract tests
        run: npx dredd arithmetic-api.contract-tests.yml http://localhost -l error
      - run: docker stop api-local-instance-for-contract-testing
      - run: docker rmi calc/arithmetics.api:local
  dependency-check:
    runs-on: ubuntu-latest
    name: dependency check
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK 6
        uses: actions/setup-dotnet@v1.8.0
        with:
          dotnet-version: '6.0.x'
      - name: Build dotnet projects
        run: dotnet build -c Debug src/Calculator.Services.ArithmeticOperations.Tests/Calculator.Services.ArithmeticOperations.Tests.csproj
      - uses: dependency-check/Dependency-Check_Action@main
        id: dependency-check
        with:
          project: 'template'
          path: '**/bin/Debug/net5.0/**/*.dll'
          format: 'JUNIT'
          args: >
            --scan "**/calculator-app/package*.json"
            --junitFailOnCVSS 7
      - name: upload check results
        uses: actions/upload-artifact@v2
        with:
          name: dependency-check-results
          path: ${{github.workspace}}/reports
        if: ${{ always() }}
  sonar-cloud:
    name: sonar cloud analysis
    runs-on: ubuntu-latest
    needs:
      - dotnet-build-test
      - dotnet-format
      - web-lint-test
      - spell-check
      - git-leaks
      - editorconfig-check
      - contract-testing
      - dependency-check
      - markdown-lint
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache SonarCloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v1
        with:
          path: ./.sonar/scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner
      - name: Setup .NET Core SDK 3
        uses: actions/setup-dotnet@v1.8.0
        with:
          dotnet-version: 3.1.x
      - name: Setup .NET Core SDK 6
        uses: actions/setup-dotnet@v1.8.0
        with:
          dotnet-version: '6.0.x'
      - name: Install SonarCloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        run: |
          mkdir -p ./.sonar/scanner
          dotnet tool update dotnet-sonarscanner --tool-path ./.sonar/scanner
      - name: Download api test results
        id: download-api-tests
        uses: actions/download-artifact@v2
        with:
          name: dotnet-test-results
          path: TestResults
      - name: Download web test results
        id: download-web-tests
        uses: actions/download-artifact@v2
        with:
          name: web-test-results
          path: TestResults
      - name: Download dependency check
        id: download-dependency-results
        uses: actions/download-artifact@v2
        with:
          name: dependency-check-results
          path: TestResults
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./.sonar/scanner/dotnet-sonarscanner begin /k:"MentorMate_dotnet-containers-template" /o:mentormate \
           /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url=https://sonarcloud.io \
           /d:sonar.exclusions="**/node_modules/**/*,**/*.ttf,**/*.woff2,**/Scripts/**/*,**/bootstrap*.css" \
           /d:sonar.test.inclusions="src/Calculator.Services.ArithmeticOperations.Tests/**/*,**/*.test.ts,**/calculator-e2e/**/*" \
           /d:sonar.cs.opencover.reportsPaths="${{steps.download-api-tests.outputs.download-path}}/coverage.opencover.xml" \
           /d:sonar.cs.vstest.reportsPaths="${{steps.download-api-tests.outputs.download-path}}/arithmetic-operations.unit-tests.trx" \
           /d:sonar.testExecutionReportPaths="${{steps.download-web-tests.outputs.download-path}}/test-report.xml" \
           /d:sonar.javascript.lcov.reportPaths="${{steps.download-web-tests.outputs.download-path}}/lcov.info" \
           /d:sonar.junit.reportPaths="${{steps.download-dependency-results.outputs.download-path}}/dependency-check-junit.xml"
          dotnet build
          ./.sonar/scanner/dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
  security:
    runs-on: ubuntu-latest
    needs:
      - dotnet-build-test
      - dotnet-format
      - web-lint-test
      - spell-check
      - git-leaks
      - editorconfig-check
      - contract-testing
      - dependency-check
      - markdown-lint
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/dotnet@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
           args: --file=/github/workspace/Calculator.sln
  doc-fx:
    name: documentation wiki
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    runs-on: windows-2022
    needs:
      - dotnet-build-test
      - dotnet-format
      - web-lint-test
      - spell-check
      - git-leaks
      - editorconfig-check
      - contract-testing
      - dependency-check
      - markdown-lint
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK 6
        uses: actions/setup-dotnet@v1.8.0
        with:
          dotnet-version: '6.0.x'
      - name: Setup DocFX
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install docfx
      - name: Install dependencies
        run: dotnet restore
      - name: DocFX Metadata
        run: docfx metadata .docs/docfx.json
      - name: DocFX Build
        run: docfx .docs/docfx.json
      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .docs/_site
          force_orphan: true

  publish:
    name: build and push docker
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    needs:
      - dotnet-build-test
      - dotnet-format
      - web-lint-test
      - spell-check
      - git-leaks
      - editorconfig-check
      - contract-testing
      - dependency-check
      - markdown-lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        services: [
          { 'imageName': 'calc-api', 'file': './src/Calculator.Services.ArithmeticOperations/Dockerfile' },
          { 'imageName': 'calc-web', 'file': './src/Calculator.Web/Dockerfile' }
        ]
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    permissions:
      packages: write
      contents: read
    outputs:
      calcApiImage: ${{ steps.image-tag.outputs.image-calc-api }}
      calcWebImage: ${{ steps.image-tag.outputs.image-calc-web }}
    steps:
      - uses: actions/checkout@v2
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ matrix.services.imageName }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=ref,event=branch
            type=sha
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./src
          file: ${{ matrix.services.file }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Output image tag
        id: image-tag
        run: echo "::set-output name=image-${{ matrix.services.imageName }}::${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ matrix.services.imageName }}:sha-$(git rev-parse --short HEAD)" | tr '[:upper:]' '[:lower:]'
  deploy:
    name: create or update environment
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs: [publish]
    outputs:
      fqdnWeb: ${{ steps.vars.outputs.fqdnWeb }}
      fqdnApi: ${{ steps.vars.outputs.fqdnApi }}
    steps:
      - uses: actions/checkout@main
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: deploy
        uses: azure/arm-deploy@v1
        with:
          deploymentName: container-app
          scope: subscription
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          region: WestEurope
          template: ./.github/biceps/main.bicep
          parameters: registry=ghcr.io containerRegistryUsername=${{ github.actor }} containerRegistryPassword=${{ secrets.GITHUB_TOKEN }} apiImage=${{ needs.publish.outputs.calcApiImage }} webImage=${{ needs.publish.outputs.calcWebImage }}
          failOnStdErr: false
      - name: output variables
        id: vars
        run: |
          fqdnWeb=$(az deployment sub show --query properties.outputs.fqdnWeb.value -n container-app -o tsv)
          fqdnApi=$(az deployment sub show --query properties.outputs.fqdnApi.value -n container-app -o tsv)
          echo "::set-output name=fqdnWeb::$fqdnWeb"
          echo "::set-output name=fqdnApi::$fqdnApi"
  functional-tests:
    name: functional tests
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
      - uses: actions/checkout@v2
      - name: Cache Node Modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-tests-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-tests-${{ env.cache-name }}-
            ${{ runner.os }}-tests-
      - name: npm package install
        run: npm ci --prefix ./src/Calculator.Web/calculator-e2e --cache ~/.npm --prefer-offline --no-audit --silent
      - name: web lint
        run: |
          echo '{"ENV_URL":"https://${{ needs.deploy.outputs.fqdnWeb }}"}' > src/Calculator.Web/calculator-e2e/cypress.env.json
          npm start --prefix ./src/Calculator.Web/calculator-e2e
      - name: upload functional test video
        uses: actions/upload-artifact@v2
        with:
          name: functional-test-video
          path: src/Calculator.Web/calculator-e2e/cypress/videos
        if: ${{ always() }}
      - name: upload functional test screenshots
        uses: actions/upload-artifact@v2
        with:
          name: functional-test-screenshots
          path: src/Calculator.Web/calculator-e2e/cypress/screenshots
        if: ${{ always() }}
  artillery-tests:
    name: artillery load tests
    runs-on: ubuntu-latest
    needs: [deploy]
    container: artilleryio/artillery:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Execute load tests
        run: /home/node/artillery/bin/artillery run --target https://${{ needs.deploy.outputs.fqdnApi }} arithmetic-api.load-tests.yml
  lighthouse-tests:
    name: lighthouse tests
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
      - uses: actions/checkout@v2
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: |
            https://${{ needs.deploy.outputs.fqdnWeb }}
          budgetPath: ./lighthouse-budget.json # test performance budgets
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage
  Notification:
    needs: [deploy]
    steps:
      - name: Google Chat Notification
        uses: Co-qn/google-chat-notification@releases/v1
        with:
          name: Build
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          status: ${{ job.status }}
        if: always()
